/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_llt_awse_FexUtils */

#ifndef _FEX_UTILS_
#define _FEX_UTILS_


#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:     com_llt_awse_FexUtils
 * Method:    compileFex
 * Signature: (Ljava/io/File;)[Ljava/lang/Byte;
 */
JNIEXPORT jobjectArray JNICALL Java_com_llt_awse_FexUtils_compileFex
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_llt_awse_FexUtils
 * Method:    decompileBin
 * Signature: (Ljava/io/File;)[Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_llt_awse_FexUtils_decompileBin
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif

#endif
