/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_llt_awse_FexUtils */

#ifndef _FEX_UTILS_
#define _FEX_UTILS_


#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jobjectArray JNICALL Java_com_llt_awse_FexUtils_compileFex
  (JNIEnv *, jclass, jobject);

JNIEXPORT jbyteArray JNICALL Java_com_llt_awse_FexUtils_decompileBin
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif

#endif
